"""Validated domain contracts shared by every interface and adapter."""

from article_translator.domain.enums import (
    BlockType,
    ExtractionStatus,
    JobStatus,
    ManualInsertionReason,
    ReviewStatus,
    SegmentContinuation,
    SegmentHandling,
    TranslationStyle,
)
from article_translator.domain.models import (
    DocumentTranslation,
    FootnoteDescription,
    FootnoteIdentity,
    GeneratedBlock,
    GeneratedFootnoteBlock,
    GeneratedManualInsertionBlock,
    GeneratedPagePayload,
    GeneratedTableMarkdown,
    GeneratedTablePayload,
    GeneratedTextBlock,
    JobManifest,
    PageTranslation,
    PreparedPage,
    TableReconstructionMetadata,
    TranslatedBlock,
    TranslationSettings,
)

__all__ = [
    "BlockType",
    "DocumentTranslation",
    "ExtractionStatus",
    "FootnoteDescription",
    "FootnoteIdentity",
    "GeneratedBlock",
    "GeneratedFootnoteBlock",
    "GeneratedManualInsertionBlock",
    "GeneratedPagePayload",
    "GeneratedTableMarkdown",
    "GeneratedTablePayload",
    "GeneratedTextBlock",
    "JobManifest",
    "JobStatus",
    "ManualInsertionReason",
    "PageTranslation",
    "PreparedPage",
    "ReviewStatus",
    "SegmentContinuation",
    "SegmentHandling",
    "TableReconstructionMetadata",
    "TranslatedBlock",
    "TranslationSettings",
    "TranslationStyle",
]
