from pathlib import Path
from typing import Protocol

from article_translator.domain.models import (
    ArtifactRef,
    DocumentTranslation,
    JobManifest,
    PageFailure,
    PageTranslation,
)


class ArtifactRepository(Protocol):
    """Persistence boundary for a single job directory."""

    @property
    def root(self) -> Path: ...

    def has_manifest(self) -> bool: ...

    def read_manifest(self) -> JobManifest: ...

    def write_manifest(self, manifest: JobManifest) -> None: ...

    def resolve(self, reference: ArtifactRef) -> Path: ...

    def read_text(self, reference: ArtifactRef) -> str: ...

    def has_page_translation(self, page_number: int) -> bool: ...

    def read_page_translation(self, page_number: int) -> PageTranslation: ...

    def write_page_translation(self, translation: PageTranslation) -> None: ...

    def write_page_failure(self, failure: PageFailure) -> None: ...

    def clear_page_failure(self, page_number: int) -> None: ...

    def write_document(self, document: DocumentTranslation) -> Path: ...

    def read_document(self) -> DocumentTranslation: ...

    def write_markdown(self, markdown: str) -> Path: ...
